version: "3.9"

services:
  web:
    build: .
    command: gunicorn stripe_shop.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: stripe_db
      POSTGRES_USER: stripe_user
      POSTGRES_PASSWORD: stripe_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
